name: Mobile Automation Hub

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - preprod
          - prod
      test_flow:
        description: 'Workflow to Execute'
        required: true
        default: 'Onboarding'
        type: choice
        options:
          - Onboarding
          - Delivery Flow
          - Return To Store

jobs:
  run-task:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run Android Emulator & Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        target: default
        arch: x86_64
        profile: pixel
        emulator-boot-timeout: 600
        disable-animations: true
        emulator-options: >
          -no-window
          -no-audio
          -no-boot-anim
          -gpu swiftshader_indirect
          -accel off
          -no-snapshot
          -memory 2048

        script: |
          echo "🔁 Restarting ADB..."
          adb kill-server || true
          adb start-server
          adb devices

          echo "⏳ Waiting for emulator to boot..."
          adb wait-for-device

          boot_completed=""
          until [[ "$boot_completed" == "1" ]]; do
            boot_completed=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
            echo "Boot status: $boot_completed"
            sleep 5
          done

          echo "✅ Emulator booted!"

          echo "🚀 Starting Appium..."
          npx appium --log-level error &
          
          sleep 10

          echo "🔧 Setting environment variables..."

          ENV="${{ github.event.inputs.environment }}"
          FLOW="${{ github.event.inputs.test_flow }}"

          if [ -z "$ENV" ]; then 
            ENV="staging"
            echo "Default ENV: $ENV"
          fi

          if [ -z "$FLOW" ]; then 
            FLOW="Onboarding"
            echo "Default FLOW: $FLOW"
          fi

          if [ "$FLOW" == "Onboarding" ]; then
            SPEC_FILE="tests/Smoke/Onboarding.ts"
          elif [ "$FLOW" == "Delivery Flow" ]; then
            SPEC_FILE="tests/Smoke/Delivery.ts"
          elif [ "$FLOW" == "Return To Store" ]; then
            SPEC_FILE="tests/Smoke/Return.ts"
          else
            echo "❌ Invalid flow"
            exit 1
          fi

          echo "🧪 Running tests..."
          npm run test:$ENV -- --spec $SPEC_FILE